name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-solver-registry:
    name: Build Solver Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.14.2/cargo-near-installer.sh | sh
      - name: Build
        run: |
          cd contracts/solver-registry
          cargo near build reproducible-wasm

  build-intents-vault:
    name: Build Intents Vault
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.14.2/cargo-near-installer.sh | sh
      - name: Build
        run: |
          cd contracts/intents-vault
          cargo near build reproducible-wasm
